Place bundled library under src folder
All recent versions of the Arduino IDE restrict recursive compilation to the src subfolder of the sketch folder. The previous use of the lib folder to store the bundled library caused compilation to fail:

C:\Users\per\AppData\Local\Temp\ccJTFh0h.ltrans0.ltrans.o: In function `setup':

C:\Users\per\Desktop\G27_Pedals_and_Shifter/G27_Pedals_and_Shifter.ino:359: undefined reference to `G27'

C:\Users\per\Desktop\G27_Pedals_and_Shifter/G27_Pedals_and_Shifter.ino:359: undefined reference to `G27'

C:\Users\per\Desktop\G27_Pedals_and_Shifter/G27_Pedals_and_Shifter.ino:359: undefined reference to `G27_::begin(bool)'

etc.

Reference:
https://github.com/arduino/arduino-builder/pull/148